config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  get '/privacy_policy', to: 'home#privacy_policy'

  resources :account_requests, only: [:new, :create]
end

app/models/account_request.rb
class AccountRequest < ApplicationRecord

  validates :name, presence: true
  validates :email, presence: true
  validates :request_type, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/account_requests_controller.rb
class AccountRequestsController < ApplicationController
  def new
    @account_request = AccountRequest.new
  end

  def create
    @account_request = AccountRequest.new(account_request_params)

    if @account_request.save
      redirect_to root_path, notice: 'Your request has been received successfully'
    else
      render :new
    end
  end

  private

  def account_request_params
    params.require(:account_request).permit(:name, :email, :request_type, :message)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/account_requests_helper.rb
module AccountRequestsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/account_requests/new.html.erb
<header class="header navbar-area">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-12">
        <div class="nav-inner">

          <nav class="navbar contact-nav-bar">
            <%= link_to root_path, class: 'navbar-brand' do %>
              <%= image_tag 'logo.png', alt: 'logo' %>
            <% end %>
            <div class="button add-list-button">
              <a href="https://play.google.com/store/apps/details?id=com.jacknkiarie.taskbud" class="btn">Get it now</a>
            </div>
          </nav>

        </div>
      </div>
    </div>
  </div>
</header>


<section id="home" class="hero-area">
  <div class="contact-form-head">
    <div class="contact-form-header">
      <h2>Request Account Deletion</h2>
      <p class="contact-form-description">Please use the form below to request Taskbud mobile app to delete your account and/or your data. This includes all tasks created. Once submitted, your data will be deleted within 7 days. This action is not reversible</p>
    </div>
    <div class="container contact-form">
      <div class="col-lg-6 col-md-12 col-12">
        <div class="form-main">
          <%= form_with model: @account_request, class: 'form' do |f| %>
            <div class="row">
              <div class="col-12">
                <div class="form-group">
                  <%= f.text_field :name, placeholder: 'Your Name', required: true %>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="col-12">
                <div class="form-group">
                  <%= f.email_field :email, placeholder: 'Your Email', required: true %>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="col-12">
                <div class="form-group">
                  <%= f.select :request_type, [['Delete Account and data', 'delete_all'], ['Delete only data', 'delete_data']], { prompt: 'Select what data we should delete' }, { class: 'form-select'} %>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="col-12">
                <div class="form-group">
                  <%= f.text_area :message, placeholder: 'Additional message (optional)' %>
                </div>
              </div>
            </div>

            <div class="col-12">
              <div class="form-group button">
                <%= f.submit 'Submit Request', class: 'btn' %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/home/index.html.erb
<!--[if lte IE 9]>
<p class="browserupgrade">
  You are using an <strong>outdated</strong> browser. Please
  <a href="https://browsehappy.com/">upgrade your browser</a> to improve
  your experience and security.
</p>
<![endif]-->


<header class="header navbar-area">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-12">
        <div class="nav-inner">

          <nav class="navbar navbar-expand-lg">
            <%= link_to root_path, class: 'navbar-brand' do %>
              <%= image_tag 'logo.png', alt: 'logo' %>
            <% end %>
            <button class="navbar-toggler mobile-menu-btn" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="toggler-icon"></span>
              <span class="toggler-icon"></span>
              <span class="toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse sub-menu-bar" id="navbarSupportedContent">
              <ul id="nav" class="navbar-nav ms-auto">
                <li class="nav-item">
                  <a href="#home" class="page-scroll active" aria-label="Toggle navigation">Home</a>
                </li>
                <li class="nav-item">
                  <a href="#features" class="page-scroll" aria-label="Toggle navigation">Features</a>
                </li>
                <li class="nav-item">
                  <a href="#overview" class="page-scroll" aria-label="Toggle navigation">Overview</a>
                </li>
                <li class="nav-item">
                  <a href="#pricing" class="page-scroll" aria-label="Toggle navigation">Pricing</a>
                </li>
                <li class="nav-item">
                  <a href="#team" class="page-scroll" aria-label="Toggle navigation">Team</a>
                </li>
              </ul>
            </div>
            <div class="button add-list-button">
              <a href="https://play.google.com/store/apps/details?id=com.jacknkiarie.taskbud" class="btn">Get it now</a>
            </div>
          </nav>

        </div>
      </div>
    </div>
  </div>
</header>


<section id="home" class="hero-area">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-5 col-md-12 col-12">
        <div class="hero-content">
          <h1 class="wow fadeInLeft" data-wow-delay=".4s">A powerful app to arrange your day.</h1>
          <p class="wow fadeInLeft" data-wow-delay=".6s">Revamp your task management with Taskbud. There’s never been a better time to be organized. Download Taskbud now!</p>
          <div class="button wow fadeInLeft" data-wow-delay=".8s">
            <a href="https://play.google.com/store/apps/details?id=com.jacknkiarie.taskbud" class="btn btn-alt"><i class="lni lni-play-store"></i> Google
              Play</a>
          </div>
        </div>
      </div>
      <div class="col-lg-7 col-md-12 col-12">
        <div class="hero-image wow fadeInRight" data-wow-delay=".4s">
          <%= image_tag 'app_splash.png', width: '600', height: '800', alt: '#' %>
        </div>
      </div>
    </div>
  </div>
</section>


<section id="features" class="features section">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <div class="section-title">
          <h3 class="wow zoomIn" data-wow-delay=".2s">Features</h3>
          <h2 class="wow fadeInUp" data-wow-delay=".4s">Your Experience Gets Better And Better Over Time.
          </h2>
          <p class="wow fadeInUp" data-wow-delay=".6s">Don't take our word for it. TaskBud’s got unique and cool features that are going to turn the tide on your everyday grind in a blink.</p>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-4 col-md-6 col-12">

        <div class="single-feature wow fadeInUp" data-wow-delay=".2s">
          <i class="lni lni-cloud-upload"></i>
          <h3>Task Creation</h3>
          <p>Create tasks with ease, just type and hit the done button!</p>
        </div>

      </div>
      <div class="col-lg-4 col-md-6 col-12">

        <div class="single-feature wow fadeInUp" data-wow-delay=".4s">
          <i class="lni lni-alarm"></i>
          <h3>Notification Reminders</h3>
          <p>Go beyond a simple task list. Never forget a task again with timely reminders.</p>
        </div>

      </div>
      <div class="col-lg-4 col-md-6 col-12">

        <div class="single-feature wow fadeInUp" data-wow-delay=".6s">
          <i class="lni lni-reload"></i>
          <h3>Task Completion</h3>
          <p>Mark your tasks as completed and watch them cross-out through the day, it‘s your victory!</p>
        </div>

      </div>
      <div class="col-lg-4 col-md-6 col-12">

        <div class="single-feature wow fadeInUp" data-wow-delay=".2s">
          <i class="lni lni-shield"></i>
          <h3>Daily Calendar View</h3>
          <p>Get your day’s tasks at a glance, neat and organized.</p>
        </div>

      </div>
      <div class="col-lg-4 col-md-6 col-12">

        <div class="single-feature wow fadeInUp" data-wow-delay=".4s">
          <i class="lni lni-cog"></i>
          <h3>Tasks Tracker</h3>
          <p>Let Taskbud keep track and help you visualize your to-do list through a monthly snapshot</p>
        </div>

      </div>
      <div class="col-lg-4 col-md-6 col-12">

        <div class="single-feature wow fadeInUp" data-wow-delay=".6s">
          <i class="lni lni-layers"></i>
          <h3>Offline Support</h3>
          <p>Create and complete your tasks and sync with the cloud when you get back online</p>
        </div>

      </div>
    </div>
  </div>
</section>


<section id="overview" class="app-info section">
  <div class="container">
    <div class="info-one">
      <div class="row align-items-center">
        <div class="col-lg-6 col-md-12 col-12">

          <div class="info-text wow fadeInLeft" data-wow-delay=".3s">
            <div class="main-icon">
              <i class="lni lni-inbox"></i>
            </div>
            <h2>Daily snapshot</h2>
            <p>Whether you’re a CEO, a wizard of Hyperbolic Time Chamber, or a goldfish with memory issues, you’re bound to love Taskbud. This smart app collects your to-dos. No fuss. No confusion. A dash of fun, a pinch of efficiency, and a load of organization!</p>
            <div class="button">
              <a href="https://play.google.com/store/apps/details?id=com.jacknkiarie.taskbud" class="btn">Get Started</a>
            </div>
          </div>

        </div>
        <div class="col-lg-6 col-md-12 col-12">
          <div class="info-image wow fadeInRight" data-wow-delay=".5s">
            <%= image_tag 'home.png', height: 600, alt: 'app home screen' %>
          </div>
        </div>
      </div>
    </div>
    <div class="info-one style2">
      <div class="row align-items-center">
        <div class="col-lg-6 col-md-12 col-12">
          <div class="info-image wow fadeInLeft" data-wow-delay=".3s">
            <%= image_tag 'profile.png', height: 600, alt: 'app profile screen' %>
          </div>
        </div>
        <div class="col-lg-6 col-md-12 col-12">

          <div class="info-text wow fadeInRight" data-wow-delay=".5s">
            <div class="main-icon">
              <i class="lni lni-layout"></i>
            </div>
            <h2>Monthly Overview</h2>
            <p>We get it, remembering one task is easy. Remembering twenty-three? Absolute chaos. Don’t you worry, Taskbud has got your back.</p>
            <div class="button">
              <a href="https://play.google.com/store/apps/details?id=com.jacknkiarie.taskbud" class="btn">Get Started</a>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</section>


<section class="section call-action">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 offset-lg-2 col-md-12 col-12">
        <div class="cta-content">
          <h2 class="wow fadeInUp" data-wow-delay=".2s">Install Taskbud and Start Using</h2>
          <p class="wow fadeInUp" data-wow-delay=".4s">Ready to make your life easier? Download Taskbud—your route to organization. Track. Complete. Celebrate. One task at a time.</p>
          <div class="button wow fadeInUp" data-wow-delay=".6s">
            <a href="https://play.google.com/store/apps/details?id=com.jacknkiarie.taskbud" class="btn btn-alt"><i class="lni lni-play-store"></i> Google
              Play</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>


<a href="#" class="scroll-top">
  <i class="lni lni-chevron-up"></i>
</a>

app/views/home/privacy_policy.html.erb
<header class="header navbar-area privacy-header">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-12">
        <div class="nav-inner">

          <nav class="navbar navbar-expand-lg">
            <%= link_to root_path, class: 'navbar-brand' do %>
              <%= image_tag 'logo.png', alt: 'logo' %>
            <% end %>
            <button class="navbar-toggler mobile-menu-btn" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="toggler-icon"></span>
              <span class="toggler-icon"></span>
              <span class="toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse sub-menu-bar" id="navbarSupportedContent">
              <ul id="nav" class="navbar-nav ms-auto">
                <li class="nav-item">
<!--                  <a href="#home" class="page-scroll active" aria-label="Toggle navigation">Home</a>-->
                  <%= link_to 'Home', root_path %>
                </li>
                <li class="nav-item">
<!--                  <a href="#features" class="page-scroll" aria-label="Toggle navigation">Features</a>-->
                  <%= link_to 'Privacy Policy', privacy_policy_path %>
                </li>
              </ul>
            </div>
            <div class="button add-list-button">
              <a href="https://play.google.com/store/apps/details?id=com.jacknkiarie.taskbud" class="btn">Get it now</a>
            </div>
          </nav>

        </div>
      </div>
    </div>
  </div>
</header>

<div class="privacy-container">
  <div class="privacy-content">
    <h1>Taskbud Privacy Policy</h1>

    <p>
      Welcome to Taskbud! Your privacy is important to us. This Privacy Policy outlines how Taskbud ("we", "us", or "our") collects, uses, and protects your personal information. By using the Taskbud Android application ("the App"), you agree to the terms and conditions outlined in this Privacy Policy.
    </p>

    <h5 class="privacy-title">Information We Collect</h5>

    <p>
      We shall employ various options in the collection of personal information. We will ensure that such processing of personal data shall be lawful, specific, and explicitly defined. Information may be voluntarily and directly collected from you, for example, during the onboarding or use of the App, or perhaps indirectly, where:

      <ul>
        <li>The data is contained in a public record, or you have made the data public.</li>
        <li>You have consented to the collection from another source.</li>
      </ul>

      Before collection of personal information and data, we shall make our best efforts, as far as is practicable, to ensure that you are reasonably informed of:

    <ul>
      <li>The use to which your personal data shall be put, your right to access your data, the right to object to processing of all or part of your data and the right to correction and deletion of false or misleading data.</li>
      <li>The fact that personal data is being collected.</li>
      <li>The purpose for which the personal data is being collected</li>
    </ul>
    </p>

    <h5 class="privacy-title">Data Retention</h5>

    <p>We retain your information only for as long as necessary for the purposes outlined in this Privacy Policy. You can delete your account at any time, which will remove your personal information and task data from our servers.</p>

    <h5 class="privacy-title">Third-Party Sharing</h5>

    <p>Taskbud does not share your personal information or task data with third parties.</p>

    <h5 class="privacy-title">Children's Privacy</h5>

    <p>Taskbud is not intended for children under the age of 13. We do not knowingly collect personal information from children.</p>
    <h5 class="privacy-title">Changes to Privacy Policy</h5>

    <p>We may update this Privacy Policy from time to time, and any changes will be reflected in the App. Please review the Privacy Policy periodically for updates.</p>

    <h5 class="privacy-title">Data deletion</h5>

    <p>Within 36 hours of us receiving your request, we shall communicate in writing with your request and inform you of the expected timeline. In all instances where legal or regulatory requirements prevent us from deleting the data as requested, Taskbud shall ensure that all Data processing (other than that legally mandated) ceases on such data immediately and that you are informed, within a reasonable time, that such deletion cannot occur but that all processing has ceased, or as the case may be.

    <h3 class="privacy-title">Contact Us</h3>

    <p>If you have any questions or concerns about this Privacy Policy, please contact us at jacknkiarie@gmail.com.

      Thank you for trusting Taskbud with your information. Task wisely!</p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taskbud</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <% if notice %>
  <div class="flash-messages">
    <div class="alert alert-primary" role="alert">
      <%= notice %>
    </div>
  </div>
  <% end %>
    <%= yield %>
  </body>
</html>